kumuluzee:
  name: quizz-service
  version: 1.0.0-SNAPSHOT
  env:
    prod: false
    name: dev
  server:
    show-server-info: false
    base-url: http://localhost:8080
    http:
      port: 8080
  cors-filter:
    servlet:
      allow-origin: "*"
      supported-methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD"
      exposed-headers: "X-Total-Count,X-Device-Id"
  openapi-mp:
    enabled: true
    servlet:
      mapping: /openapi/specs
    ui:
      enabled: true
      mapping: /openapi/ui
  logs:
    loggers:
      - name: ''
        level: INFO
  health:
    servlet:
      mapping: /health/
      enabled: true
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/mainDB
      disk-space-health-check:
        threshold: 100000000
        type: liveness
  datasources:
    - jndi-name: jdbc/mainDB
      connection-url: jdbc:postgresql://localhost:5432/quizz-service
      username: postgres
      password: postgres
      pool:
        max-size: 5
kee-auth:
  oidc:
    auto-configure: true,
    well-known-url: https://keycloak.mjamsek.com/auth/realms/ioi-projekt/.well-known/openid-configuration
quizz:
  durations:
    loading: 3
    question: 5
  groups:
    members:
      limit: 4
